shinyUI(fluidPage(theme = "bootstrap.css",
                  
  br(),
  
  sidebarLayout(
    sidebarPanel(
      img(src = "harbin_logo_final.png", height = 400, width = 400),
      br(),
      br(),
      strong(h4("Relative quantitation data analysis tool for real-time qPCR data.", align="center")),
      br(),
      p("For example data and instructions, visit the Harbin homepage at ",
        a("https://github.com/Rbester18/harbin.", 
          href = "https://github.com/Rbester18/harbin")),
      downloadButton(
        "manual","Download instruction manual"),
      br(),
      br(),
      p("* Version:	0.1"),
      p("* Date:	2016-03-01"),
      p("* License:	GPL-3"),
      br(),
      p("If you use this application, please cite:"),
      em("Bester, R, Pepler, PT, Burger, JT. and Maree, HJ. (2016). Harbin: An analysis tool for relative quantitation of real-time qPCR data and a quantile-based bootstrap test for data pooling."),
      br(),
      br(),
      img(src = "Vitis_logo.jpg", height = 80, width = 138, "Harbin is a product from the ", 
      a("Vitis laboratory.", href="http://www.sun.ac.za/english/faculty/agri/genetics/research/plant-genetics"), align="right"), 
      "For more information please contact Dr. H.J. Maree at hjmaree@sun.ac.za",
      br(),
      br(),
      h6(em("'Robert Harbin (1908 - 1978), born in South Africa, was a British magician and the inventor of a number of classic illusions, including the Zig Zag Girl. Since the the qPCR concentrations are devided into intervals, we decided to name our application ", span("Harbin", style = "color:#dd4814"), "'"))
    ),
    
    mainPanel(
      tabsetPanel(tabPanel(h5("Data upload"),
                           br(),
                 navlistPanel("Import data",
                  tabPanel(h5("Rotor-Gene data import"),
                          strong(h4("Select data")),
                          em("Applicable for Rotor-Gene Q software version 2.3.11 and above"),
                          helpText("Load all .csv files from your gene of interest (GOI). Including standard curve data (Upload allows for multiple selection)."),
                          fluidRow(
                            column(6, fileInput("GOI", 
                                    label = "Gene of interest files (GOI)", multiple =TRUE)),
                            column(6,downloadButton(
                            "Examplefile",
                            "Download example file"
                          ))),
                          selectInput("refgenenum.answer", "Select number of reference genes", choices = seq(1,10,1), selected=3),
                          helpText("Load all .csv files per reference gene. Including standard curve data (Upload allows for multiple selection)."),
                          uiOutput("input_ref"),
                          strong(h4("Check to confirm that samples match between genes.")), 
                          helpText("Comparison to gene of interest per reference gene"),
                          verbatimTextOutput("NO_GOI_1"),
                          verbatimTextOutput("NO_GOI_2"),
                          verbatimTextOutput("NO_GOI_3"),
                          br(),
                          br()
                          ),
                      navbarMenu("--> Rotor-Gene data output",
                        tabPanel("Gene of interest data",
                                     tableOutput("GOI_o")),
                        tabPanel("Reference gene data",
                                     tableOutput("RG_o")),
                        tabPanel("Normalised data",
                                     h5("Normalised GOI data"),
                                     tableOutput("GOI_norm_table"))
                               ),
                    tabPanel(h5("Manual data import"),
                          strong(h4("Select data")),
                          dateInput("expdate", 
                                    label = "Experiment date input", 
                                    value = "2016-02-01"),
                          fluidRow(
                            column(6, fileInput("Cqvals", 
                                    label = "Comma-separted file containing GOI and reference gene Cq values per column")),
                            column(6, downloadButton("Examplefilem", "Download example file"))),
                          strong(h4("Enter standard curve information for gene of interest")),
                          fluidRow(
                            column(6, numericInput("GOIslope", 
                                       "Gene of interest slope", value = -3.2)),
                            column(6, numericInput("GOIintercept", 
                                       label = "Gene of interest y-intercept", value = 20))),
                          fluidRow(
                            column(6, numericInput("GOI_SD_min", 
                                       label = "Minimum Cq of standard curve for gene of interest",
                                       value = 15.1)),
                            column(6, numericInput("GOI_SD_max", 
                                       label = "Maximum Cq of standard curve for gene of interets",
                                       value = 30.1))),
                          strong(h4("Enter standard curve information for each reference gene")),
                          sliderInput("num_refgenes", "Number of reference genes",
                                      min = 1, max = 10, value = 3),
                          fluidRow(
                            column(6, uiOutput("Ref_slopes")),
                            column(6, uiOutput("Ref_intercept"))),
                          fluidRow(
                            column(6, uiOutput("SD_min")),
                            column(6, uiOutput("SD_max")))),
                        navbarMenu("--> Manual import data output",
                            tabPanel("Gene of interest data",
                                     tableOutput("GOI_om")),
                            tabPanel("Reference gene data",
                                     tableOutput("RG_om")),
                            tabPanel("Normalised data",
                                     h5("Normalised GOI data"),
                                     tableOutput("GOI_norm_table_m"))
                          ))),
                 tabPanel(h5("Harbin intervals"),
                    navlistPanel("Database comparison",
                      tabPanel(h4("Rotor-Gene data import comparison"), 
                          h5("Do you want to compare normalised data to an existing reference database file?"),
                          radioButtons("Database", "Compare to reference database file?", 
                                       choices = list("Yes" = 1, "No" = 2), selected=2),
                          fluidRow(
                            column(6, uiOutput("refdb")),
                            column(6, downloadButton("RD_Examplefile", "Download database example file"))),
                          uiOutput("Harbindescribe"),
                          uiOutput("Harbintesttype"),
                          h5("Database comparison"),
                          verbatimTextOutput("line1"),
                          verbatimTextOutput("numchange"),
                          verbatimTextOutput("line2"),
                          verbatimTextOutput("line3"),
                          verbatimTextOutput("line4"),
                          verbatimTextOutput("line5"),
                          verbatimTextOutput("duplicated_names"),
                          radioButtons("Database_add", "Do you want to add data to reference database file?", 
                                       choices = list("Yes" = 1, "No" = 2), selected=2),
                          h5("Download normalised gene of interest(GOI) data and new reference database (if applicable)"),
                          downloadButton('downloadGOI', 'Download normalised GOI data'),
                          downloadButton('downloadDB', 'Download new database'),
                          br(),
                          br(),
                          br()
                          ),
                      navbarMenu(h6("--> Rotor-Gene import: View reference database"),
                      tabPanel("Reference database",
                                  tableOutput("RD_o"))),
                  tabPanel(h4("Manual data import comparison"),
                           h5("Do you want to compare normalised data to an existing reference database file?"),
                      radioButtons("Database_m", "Do you want to compare data to a reference database file?", 
                                   choices = list("Yes" = 1, "No" = 2), selected=2),
                      fluidRow(
                        column(6, uiOutput("refdbm")),
                      column(6, downloadButton("RD_Examplefile_m", "Download database example file"))),
                      uiOutput("Harbindescribe_m"),
                      uiOutput("Harbintesttype_m"),
                      h5("Database comparison"),
                      verbatimTextOutput("line1_2"),
                      verbatimTextOutput("numchange_2"),
                      verbatimTextOutput("line2_2"),
                      verbatimTextOutput("line3_2"),
                      verbatimTextOutput("line4_2"),
                      verbatimTextOutput("line5_2"),
                      verbatimTextOutput("duplicated_names_m"),
                      radioButtons("Database_add_m", "Do you want to add data to reference database file?", 
                                   choices = list("Yes" = 1, "No" = 2), selected=2),
                      h5("Download normalised gene of interest(GOI) data and new reference database (if applicable)"),
                      downloadButton('downloadGOIm', 'Download normalised GOI data'),
                      downloadButton('downloadDBm', 'Download new database'),
                      br(),
                      br(),
                      br()),
                  navbarMenu(h6("--> Manual import:View reference database"),
                             tabPanel("Reference database",
                                      tableOutput("RD_om"))),
                  tabPanel(h4("Interval visualisation"),
                           strong(h4("Normalised concentration values and interval distribution comparisons")),
                           radioButtons("Input_type", "Rotor-Gene or manual input?", 
                                        choices = list("Rotor-Gene input" = 1, "Manual input" = 2), selected=1),
                           helpText("Intervals are indicated with dotted lines"),
                           plotOutput("intervalbarplot"))
                      )),
                 tabPanel(h5("Group selection"),
                          strong(h4("Data transformation")),
                          radioButtons("logtransform", 
                                             label = "Do you want to transform concentrations values?", 
                                             choices = list("Natural log" = 1, 
                                                            "log base 10" = 2, "No transformation"=3),
                                             selected = 3),
                          strong(h4("Select dataset to use for statistical analysis")),
                          helpText(em("Normalised data: Data from Rotor-Gene/manual input")), 
                          helpText(em("New reference database: Data from Rotor-Gene/manual input if option was selected to add data to reference database")),
                          helpText(em("Other file: Data from previous analysis")),
                          radioButtons("file_choice", label="File options",
                                       choices = list("Normalised data" = 1, "New reference database (if applicable)" = 2,
                                                      "Other file" = 3),selected = 1),
                          uiOutput("NormNew"),
                          strong(h4("Categorised samples into groups by selecting the applicable rows per group")),
                          selectInput("num_groups", "Select number of groups", choices = seq(2,5,1), selected=2),
                          h5("Select rows for group 1."),
                          DT::dataTableOutput('table1'),
                          verbatimTextOutput('table1_2'),
                          h5("Select rows for group 2."),
                          DT::dataTableOutput('table2'),
                          verbatimTextOutput('table2_1'),
                          h5("Select rows for group 3."),
                          DT::dataTableOutput('table3'),
                          verbatimTextOutput('table3_1'),
                          h5("Select rows for group 4."),
                          DT::dataTableOutput('table4'),
                          verbatimTextOutput('table4_1'),
                          h5("Select rows for group 5."),
                          DT::dataTableOutput('table5'),
                          verbatimTextOutput('table5_1'),
                          br(),
                          br(),
                          br()
                 ),
                 tabPanel(h5("Data distribution"),
                          strong(h4("Use this page to evaluate normal distribution and homoscedasticity of data in order to decide on the appropiate statistical test.")),
                          h5("Basic statistics"),
                          verbatimTextOutput("textarea.out"),
                          br(),
                          h5("Overlayed histograms"),
                          plotOutput("distPlot"),
                          h5("Box plots with individual data points"),
                          plotOutput("boxPlot", width="80%"),
                          br(),
                          h5("Normal distribution tests"),
                          verbatimTextOutput("testnorm.out"),
                          br(),
                          h5("Levene's test for equality of variances"),
                          verbatimTextOutput("levene.out")
                 ),
                 navbarMenu(h5("Statistical tests"),
                   tabPanel("Parametric tests",
                          strong(h4("Statistical analysis for normal distributed data.")),
                          h4("Two independent groups"),
                          h5("Independent t-test"),
                          verbatimTextOutput("t.out"),
                          h4("Three or more independent groups"),
                          h5("ANOVA"),
                          verbatimTextOutput("anova")      
                 ),
                   tabPanel("Non-parametric tests",
                          strong(h4("Statistical analysis for data that do not follow a normal distribution.")),
                          h4("Two independent groups"),
                          h5("Wilcoxon rank sum test"),
                          verbatimTextOutput("wilcox"),
                          h4("Three or more independent groups"),
                          h5("Kruskal Wallis test"),
                          verbatimTextOutput("KrWs")
                          ))       
      )
    )
  )
))

